Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox"
  config.vm.network :forwarded_port, host: 4567, guest: 80
  config.vm.provision :shell, :path => "install_apache.sh"
end
